version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10

save_git: &save_git
  save_cache:
    key: code-{{ .Revision }}
    paths:
      # save git commit and ssh config
      - .git

restore_git: &restore_git
  restore_cache:
    key: code-{{ .Revision }}

save_dep: &save_dep
  save_cache:
    key: dep-{{ checksum "yarn.lock" }}
    paths:
      # save git commit and ssh config
      - node_modules

restore_dep: &restore_dep
  restore_cache:
    key: dep-{{ checksum "yarn.lock" }}

jobs:
  # lockfile:
  #   <<: *defaults
  #   steps:
  #     - <<: *restore_git
  #     - checkout
  #     - run:
  #         name: "greenkeeper update yarn.lock"
  #         command: |
  #           sudo yarn global add greenkeeper-lockfile@2
  #           greenkeeper-lockfile-update

  #     - <<: *save_git

  build:
    <<: *defaults
    steps:
      - <<: *restore_git
      - checkout

      - <<: *restore_dep

      - run: yarn --frozen-lockfile
      - run: yarn build

      - <<: *save_dep
      # - run:
      #     name: "greenkeeper-lockfile-upload"
      #     command: |
      #       sudo yarn global add greenkeeper-lockfile@2
      #       greenkeeper-lockfile-upload

      - <<: *save_git

      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  run-tests:
    <<: *defaults
    steps:
      - <<: *restore_git
      - checkout

      - <<: *restore_dep

      - run: yarn --frozen-lockfile

      - attach_workspace:
          at: ~/project

      - run: yarn test

      # - run:
      #     name: "greenkeeper-lockfile-upload"
      #     command: |
      #       sudo yarn global add greenkeeper-lockfile@2
      #       greenkeeper-lockfile-upload

      - <<: *save_git

  run-lint:
    <<: *defaults
    steps:
      - <<: *restore_git
      - checkout

      - <<: *restore_dep

      - run: yarn --frozen-lockfile

      - attach_workspace:
          at: ~/project

      - run: yarn lint


workflows:
  run-lib-test:
    jobs:
      # - lockfile
      - build
          # requires:
          #   - lockfile

      - run-lint:
          requires:
            - build

      - run-tests:
          requires:
            - build
