version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run: cat package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile
      - run: yarn build

      - save_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  run-tests:
    <<: *defaults
    steps:
      - checkout

      - run: cat package.json yarn.lock | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile

      - attach_workspace:
          at: ~/project

      - run: yarn test

  run-lint:
    <<: *defaults
    steps:
      - checkout

      - run: cat package.json yarn.lock | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile

      - attach_workspace:
          at: ~/project

      - run: yarn lint


workflows:
  run-lib-test:
    jobs:
      - build

      - run-lint:
          requires:
            - build

      - run-tests:
          requires:
            - build
