version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10

save: &save
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .
      # save git commit and ssh config
      - .git
      - ~/.ssh

restore: &restore
  restore_cache:
    key: code-{{ .Revision }}

jobs:
  lockfile:
    <<: *defaults
    steps:
      - checkout
      - run: "sudo yarn global add greenkeeper-lockfile@2"
      - run: "greenkeeper-lockfile-update"
      - run: "echo job1 installed greenkeeper-lockfile and ran greenkeeper-lockfile-update"
      - <<: *save

  build:
    <<: *defaults
    steps:
      - <<: *restore
      - run: cat package.json yarn.lock | shasum > .dependencies_checksum

      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile
      - run: yarn build

      - save_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  run-tests:
    <<: *defaults
    steps:
      - <<: *restore
      - run: 'sudo yarn global add greenkeeper-lockfile@2'

      - run: cat package.json yarn.lock | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile

      - attach_workspace:
          at: ~/project

      - run: yarn test
      - run: greenkeeper-lockfile-upload

  run-lint:
    <<: *defaults
    steps:
      - <<: *restore

      - run: cat package.json yarn.lock | shasum > .dependencies_checksum
      - restore_cache:
          key: dependency-cache-{{ checksum ".dependencies_checksum" }}

      - run: yarn --frozen-lockfile

      - attach_workspace:
          at: ~/project

      - run: yarn lint


workflows:
  run-lib-test:
    jobs:
      - lockfile
      - build:
          requires:
            - lockfile

      - run-lint:
          requires:
            - build

      - run-tests:
          requires:
            - build
